### ISSUE TITLE
ClusterDuckType needs to validate the aggragating role is present.

### ISSUE THREAD

**Issue by n3wscott** [knative-sandbox/discovery#138]
For our duck types to work, we use an aggregating RBAC label to allow rights to the duck type. It would be nice if the cluster duck type would test this and report back in the status. This could  adding a label and roles to the versioned duck in status to report what we found. This likely will require an additional label to be specified in the spec. This will take some experimenting, there are some limitations to the kinds of RBAC a controller can make.

**Comment by xtreme-sameer-vohra** [comment]
#Checklist
- [ ] expose option to configure role ref in ClusterDuckType
- [ ] display role ref in status
- [ ] validate role exists
- [ ] validate if role has access to list of Ducks

**Comment by xtreme-sameer-vohra** [comment]
With no modifications to the current service account, the controller isn't able to access cluster roles, which might be obvious :)

```
  Warning  InternalError  1s (x12 over 6s)  clusterducktype-controller  clusterroles.rbac.authorization.k8s.io "addressable-resolver" is forbidden: User "system:serviceaccount:knative-discovery:controller" cannot get resource "clusterroles" in API group "rbac.authorization.k8s.io" at the cluster scope
```
